spring:
  profiles:
    group:
      local: [local, common]
      test: [test, common]
    active: local
  config:
    import: optional:.env[.properties]

---
spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:TEST}
            client-secret: ${KAKAO_CLIENT_SECRET:TEST}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: ${NAVER_CLIENT_ID:TEST}
            client-secret: ${NAVER_CLIENT_SECRET:TEST}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: /
  error:
    include-message: always
  forward-headers-strategy: framework

springdoc:
  packages-to-scan:
    - com.lucas.aladin.controllers
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
    operations-sorter: method
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /v1/**

jwt:
  secret: ${JWT_SECRET:hL5y2w8rhW3PfK8D3R0VuTJY8Tg0rV9tqBiUXu3/1yo=}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:sqlite:./todo.db
    driver-class-name: org.sqlite.JDBC

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:sqlite:./todo-test.db # ✅ 테스트 전용 SQLite 파일
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create-drop
